#!/usr/bin/env python3
"""Compare bridge_raw_tester run outputs from oracle vs firmware paths.

This script helps identify command-shape and response differences by label
and sent frame bytes, using JSON outputs generated by scripts/bridge_raw_tester.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_run(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or "results" not in payload:
        raise ValueError(f"invalid bridge_raw_tester payload: {path}")
    return payload


def _attempt_rx_values(case: dict[str, Any]) -> set[str]:
    values: set[str] = set()
    for attempt in case.get("attempts", []):
        rx = str(attempt.get("rxHex", "")).strip()
        values.add(rx.lower())
    return values


def _attempt_ok_values(case: dict[str, Any]) -> set[bool]:
    return {bool(attempt.get("ok", False)) for attempt in case.get("attempts", [])}


def flatten_cases(run: dict[str, Any], match_by: str) -> dict[str, dict[str, Any]]:
    flattened: dict[str, dict[str, Any]] = {}
    for case in run.get("results", []):
        label = str(case.get("label", "unnamed"))
        frame = str(case.get("frameHex", "")).lower()
        key = frame if match_by == "frame" else f"{label}|{frame}"
        flattened[key] = {
            "label": label,
            "frameHex": frame,
            "rxValues": sorted(_attempt_rx_values(case)),
            "okValues": sorted(_attempt_ok_values(case)),
            "attemptCount": len(case.get("attempts", [])),
        }
    return flattened


def build_summary(
    oracle_cases: dict[str, dict[str, Any]], firmware_cases: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    all_keys = sorted(set(oracle_cases) | set(firmware_cases))
    rows: list[dict[str, Any]] = []
    matches = 0
    for key in all_keys:
        oracle = oracle_cases.get(key)
        firmware = firmware_cases.get(key)

        if oracle and firmware:
            rx_match = oracle["rxValues"] == firmware["rxValues"]
            ok_match = oracle["okValues"] == firmware["okValues"]
            fully_match = rx_match and ok_match
            if fully_match:
                matches += 1
            rows.append(
                {
                    "label": oracle["label"],
                    "frameHex": oracle["frameHex"],
                    "presentInOracle": True,
                    "presentInFirmware": True,
                    "oracleAttemptCount": oracle["attemptCount"],
                    "firmwareAttemptCount": firmware["attemptCount"],
                    "oracleOkValues": oracle["okValues"],
                    "firmwareOkValues": firmware["okValues"],
                    "oracleRxValues": oracle["rxValues"],
                    "firmwareRxValues": firmware["rxValues"],
                    "okMatch": ok_match,
                    "rxMatch": rx_match,
                    "match": fully_match,
                }
            )
            continue

        source = oracle if oracle else firmware
        assert source is not None
        rows.append(
            {
                "label": source["label"],
                "frameHex": source["frameHex"],
                "presentInOracle": bool(oracle),
                "presentInFirmware": bool(firmware),
                "oracleAttemptCount": oracle["attemptCount"] if oracle else 0,
                "firmwareAttemptCount": firmware["attemptCount"] if firmware else 0,
                "oracleOkValues": oracle["okValues"] if oracle else [],
                "firmwareOkValues": firmware["okValues"] if firmware else [],
                "oracleRxValues": oracle["rxValues"] if oracle else [],
                "firmwareRxValues": firmware["rxValues"] if firmware else [],
                "okMatch": False,
                "rxMatch": False,
                "match": False,
            }
        )

    return {
        "caseCountCompared": len(rows),
        "fullMatches": matches,
        "rows": rows,
    }


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Compare two bridge_raw_tester JSON outputs.")
    parser.add_argument("--oracle-run", type=Path, required=True, help="Known-good reference run JSON")
    parser.add_argument("--firmware-run", type=Path, required=True, help="Current firmware run JSON")
    parser.add_argument(
        "--match-by",
        choices=["label_frame", "frame"],
        default="label_frame",
        help="Case matching strategy (default: label_frame)",
    )
    parser.add_argument("--out", type=Path, help="Optional output report JSON path")
    return parser


def main() -> int:
    args = build_arg_parser().parse_args()
    oracle = load_run(args.oracle_run)
    firmware = load_run(args.firmware_run)
    summary = build_summary(
        flatten_cases(oracle, args.match_by),
        flatten_cases(firmware, args.match_by),
    )
    payload = {
        "oracleRun": str(args.oracle_run),
        "firmwareRun": str(args.firmware_run),
        "matchBy": args.match_by,
        **summary,
    }
    formatted = json.dumps(payload, indent=2)
    print(formatted)
    if args.out:
        args.out.write_text(formatted + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
